import { Rubik } from "next/font/google";
import "../app/globals.css";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "The Sponsor Match",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {

  return (
    <html>
      <body className={rubik.className}>{children}</body>
    </html>
  );
}
