import "../globals.css";

export const metadata = {
  title: "The Sponsor Match",
  description: "Generated by create next app",
  icon: "/icon.png"
};

export default function Layout({ children }) {
  return (
        <>
            {children}
        </>
  );
}
