import { Rubik } from "next/font/google";
import "../globals.css";
import LandingHeader from "../ui/notLoggedIn/header/header";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "The Sponsor Match",
  description: "Generated by create next app",
  icon: "/icon.png"
};

export default function Layout({ children }) {
  return (
        <>
            <LandingHeader />
            {children}
        </>
  );
}
